<?php
include('models/connexion.php');
include('models/function.php');
include('models/newsletter.php');
include('models/admin.php');
include('models/users.php');
include('structure/front/composants/head.php');
include('structure/front/composants/header.php');
include('structure/front/composants/navbar.php');
?>